language: node_js
node_js:
  - "node"
install:
  - npm install
  - npm install -g now
script:
  - npm run lint
deploy:
  skip_cleanup: true
  provider: script
  script:
    - npm run deploy
  on:
    branch: feat/deploy
  skip_cleanup: true
  provider: script
  script:
    - npm run devdeploy
  on:
    branch: develop
